
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:super_heros/model.dart';
import 'package:super_heros/url.dart';

class ApiClass {
  ValueNotifier<List<Superheross>> productNotifier = ValueNotifier([]);
  ApiClass._internal();
  static ApiClass instance = ApiClass._internal();
  factory() {
    return instance;
  }

  final dio = Dio();
  final url = URL();

  ApiClass() {
    dio.options = BaseOptions(
      baseUrl: url.productBaseUrl,
      responseType: ResponseType.json,
    );
  }


  getProducts() async {
    final result = await dio.get(url.productBaseUrl + url.productsEndpoint);
    final getProduct = Autogenerated.fromJson(result.data);
    print("fffffff${result.data}");
    if (getProduct.superheros != null) {
      productNotifier.value.clear();
      productNotifier.value.addAll(getProduct.superheros!);
      print("666666666 $productNotifier");
    } else {
      productNotifier.value.clear();
    }
  }
}
