class Autogenerated {
  List<Superheross>? superheros;

  Autogenerated({this.superheros});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['superheros'] != null) {
      superheros = <Superheross>[];
      json['superheros'].forEach((v) {
        superheros!.add(new Superheross.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.superheros != null) {
      data['superheros'] = this.superheros!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Superheross {
  String? name;
  String? power;
  String? url;

  Superheross({this.name, this.power, this.url});

  Superheross.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    power = json['power'];
    url = json['url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['power'] = this.power;
    data['url'] = this.url;
    return data;
  }
}